apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-gateway
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: gateway
spec:
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.ports.server.gateway }}
      targetPort: gateway-port