apiVersion: v1
kind: Secret
metadata:
  name: server-secret
type: Opaque
stringData:
  mongodbUrl: {{ .Values.secrets.mongoDbUrl | quote }}
  mongodbDatabase: {{ .Values.secrets.mongodbDatabase | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
