apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-user-service
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: user
spec:
  type: ClusterIP
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.ports.server.user }}
      targetPort: user-port
