name: "Create Spring .env"
description: "Generate a .env file with all variables required by Spring services during CI"
author: "Cascade AI"
runs:
  using: "composite"
  steps:
    - name: Generate .env file
      shell: bash
      run: |
        cat <<'EOF' > .env
        # Ports
        SERVER_PORT_GATEWAY=8080
        SERVER_PORT_USER=8081
        SERVER_PORT_COURSES=8082

        # JWT (used by user-service tests)
        JWT_SECRET=test-secret
        JWT_EXPIRATION_MS=3600000
        EOF
        echo "✅ Generated .env:" && cat .env
