apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-client
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: client
spec:
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: client-port