services:
  reverse-proxy:
      image: traefik:v3.4
      container_name: traefik
      restart: unless-stopped
      command:
        - "--providers.docker=true"
        - "--providers.docker.exposedByDefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
        - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
        - "--certificatesresolvers.letsencrypt.acme.email=admin@tum.de"
        - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
        # For local test add:
        # - "--api.dashboard=true"
        # - "--api.insecure=true"
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./letsencrypt:/letsencrypt
      networks:
        - app-network
  # ─── MongoDB ──────────────────────────────────────
  mongo:
    image: mongo:7.0
    container_name: ${MONGODB_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${MONGODB_EXPOSED_PORT}:27017"
    env_file:
      - .env.prod
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\" > /dev/null 2>&1"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "none"
    networks:
      - app-network

  # ─── Spring Boot Server ──────────────────────────────
  server-gateway:
    image: ghcr.io/aet-devops25/team-git-it-together/server-gateway:latest
    container_name: ${SERVER_CONTAINER_NAME}-gateway
    restart: unless-stopped
    ports:
      - "${SERVER_PORT_GATEWAY}:${SERVER_PORT_GATEWAY}"
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILE_ACTIVES: ${SPRING_PROFILE_ACTIVES}
      SERVER_PORT_GATEWAY: ${SERVER_PORT_GATEWAY}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${SERVER_PORT_GATEWAY}/actuator/health || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`${SERVER_HOST}`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=${SERVER_PORT_GATEWAY}"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=letsencrypt"
    networks:
      - app-network
  user-service:
    image: ghcr.io/aet-devops25/team-git-it-together/user-service:latest
    container_name: ${SERVER_CONTAINER_NAME}-user
    restart: unless-stopped
    ports:
      - "${SERVER_PORT_USER}:${SERVER_PORT_USER}"
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILE_ACTIVES: ${SPRING_PROFILE_ACTIVES}
      SERVER_PORT_USER: ${SERVER_PORT_USER}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: mongo
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    depends_on:
      server-gateway:
        condition: service_healthy
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${SERVER_PORT_USER}/actuator/health || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network
  
  client:
    image: ghcr.io/aet-devops25/team-git-it-together/client:latest
    container_name: ${CLIENT_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${VITE_PORT}:3000"
    env_file:
      - .env.prod
    environment:
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    depends_on:
      user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:3000 || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.http.services.client.loadbalancer.server.port=${VITE_PORT}"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.client-compress.compress=true"
      - "traefik.http.routers.client.middlewares=client-compress"
      - "traefik.http.routers.client.priority=1"
    networks:
      - app-network
  
  weaviate-db:
      image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
      container_name: ${WEAVIATE_CONTAINER_NAME}
      restart: on-failure
      command:
        - --host
        - 0.0.0.0
        - --port
        - "8080"
        - --scheme
        - http
      ports:
        - "${WEAVIATE_EXPOSED_HTTP_PORT}:8080"
        - "${WEAVIATE_EXPOSED_GRPC_PORT}:50051"
      environment:
        QUERY_DEFAULTS_LIMIT: 25
        AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
        PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
        BACKUP_FILESYSTEM_PATH: '/var/lib/weaviate/backups'
        ENABLE_API_BASED_MODULES: 'true'
        CLUSTER_HOSTNAME: 'node1'
      volumes:
        - weaviate-genai-data:/var/lib/weaviate
      healthcheck:
        test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/v1/.well-known/ready || exit 1"]
        interval: 600s
        timeout: 10s
        retries: 3
        start_period: 50s
      networks:
        - app-network

  genai:
    image: ghcr.io/aet-devops25/team-git-it-together/genai:latest
    container_name: ${GENAI_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      WEAVIATE_HOST: ${WEAVIATE_HOST}
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_PORT: 50051
      GENAI_PORT: ${GENAI_PORT}
      GENAI_APP_NAME: ${GENAI_APP_NAME}
      GENAI_APP_VERSION: ${GENAI_APP_VERSION}
      LLM_PROVIDER: ${LLM_PROVIDER}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
    ports:
      - "${GENAI_PORT}:${GENAI_PORT}"
    depends_on:
      weaviate-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${GENAI_PORT}/ping || exit 1"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 50s
    networks:
      - app-network

volumes:
  mongo-data:
  weaviate-genai-data:

networks:
  app-network:
    driver: bridge