apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-mongodb
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: mongodb
spec:
  type: ClusterIP
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
      name: mongodb 