apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-mongodb
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "skillForgeAi.selectorLabels" . | nindent 6 }}
      component: mongodb
  template:
    metadata:
      labels:
        {{- include "skillForgeAi.selectorLabels" . | nindent 8 }}
        component: mongodb
    spec:
      containers:
        - name: {{ .Values.services.mongo }}
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
              name: mongodb-port
          livenessProbe:
            exec:
              command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
            - name: MONGO_INITDB_DATABASE
              value: "skillForge"
            - name: MONGO_INITDB_AUTH_SOURCE
              value: "admin"
            - name: MONGODB_LOG_LEVEL
              value: {{ .Values.mongodb.logging.level | quote }}
          {{- if not .Values.mongodb.logging.enabled }}
          command:
            - "mongod"
            - "--quiet"
            - "--logpath"
            - "/dev/null"
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
              memory: {{ .Values.mongodb.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
              memory: {{ .Values.mongodb.resources.limits.memory }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ include "skillForgeAi.fullname" . }}-mongodb-pvc 