apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-genai
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: genai
spec:
  type: ClusterIP
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: genai
  ports:
    - protocol: TCP
      port: {{ .Values.ports.genai }}
      targetPort: genai-port
