apiVersion: v1
kind: Secret
metadata:
  name: genai-secret
type: Opaque
stringData:
  llmProvider: {{ .Values.secrets.llmProvider | quote }}
  openaiApiBase: {{ .Values.secrets.openaiApiBase | quote }}
  openaiApiKey: {{ .Values.secrets.openaiApiKey | quote }}
  openaiModel: {{ .Values.secrets.openaiModel | quote }}
