apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skillforge-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
        - api.{{ .Values.host }}
        - prometheus.{{ .Values.host }}
        - grafana.{{ .Values.host }}
        - alertmanager.{{ .Values.host }}
        - mailhog.{{ .Values.host }}
      secretName: skillforge-tls
  rules:
    # Frontend client
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "skillForgeAi.fullname" . }}-client
                port:
                  number: 80
    # API backend
    - host: api.{{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "skillForgeAi.fullname" . }}-gateway
                port:
                  number: {{ .Values.ports.server.gateway }}
    # GenAI backend
    - host: api.genai.{{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "skillForgeAi.fullname" . }}-genai
                port:
                  number: {{ .Values.ports.genai }}
    # Prometheus monitoring
    - host: prometheus.{{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "skillForgeAi.fullname" . }}-prometheus
                port:
                  number: {{ .Values.monitoring.prometheus.port }}
    # Grafana monitoring
    - host: grafana.{{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "skillForgeAi.fullname" . }}-grafana
                port:
                  number: {{ .Values.monitoring.grafana.port }}
    # Alertmanager monitoring
    - host: alertmanager.{{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "skillForgeAi.fullname" . }}-alertmanager
                port:
                  number: {{ .Values.monitoring.alertmanager.port }}
    # MailHog email testing
    - host: mailhog.{{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "skillForgeAi.fullname" . }}-mailhog
                port:
                  number: {{ .Values.monitoring.mailhog.webPort }}