{{- if and .Values.monitoring.enabled .Values.monitoring.promtail.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-promtail
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: promtail
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.monitoring.promtail.port }}
      targetPort: promtail-port
      protocol: TCP
      name: http
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: promtail
{{- end }} 