{{- if and .Values.monitoring.enabled .Values.monitoring.promtail.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-promtail
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: promtail
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "skillForgeAi.selectorLabels" . | nindent 6 }}
      component: promtail
  template:
    metadata:
      labels:
        {{- include "skillForgeAi.selectorLabels" . | nindent 8 }}
        component: promtail
    spec:
      securityContext:
        fsGroup: 65534
        supplementalGroups:
          - 65534
      containers:
        - name: promtail
          image: "{{ .Values.monitoring.promtail.image.repository }}:{{ .Values.monitoring.promtail.image.tag }}"
          imagePullPolicy: {{ .Values.monitoring.promtail.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.monitoring.promtail.port }}
              name: promtail-port
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
          args:
            - -config.file=/etc/promtail/config.yml
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          livenessProbe:
            httpGet:
              path: /ready
              port: promtail-port
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: promtail-port
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.monitoring.promtail.resources.requests.cpu }}
              memory: {{ .Values.monitoring.promtail.resources.requests.memory }}
            limits:
              cpu: {{ .Values.monitoring.promtail.resources.limits.cpu }}
              memory: {{ .Values.monitoring.promtail.resources.limits.memory }}
      volumes:
        - name: promtail-config
          configMap:
            name: {{ include "skillForgeAi.fullname" . }}-promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
{{- end }} 