server:
  port: 8080

spring:
  application:
    name: ${APP_NAME:skill-forge-server} # default fallback to skill-forge-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:no-mongo} # default fallback to no-mongo

logging:
  level:
    root: INFO