server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SERVER_APP_NAME}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO