spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:27017/${MONGODB_DATABASE}?authSource=admin