apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-redis
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: redis-port