spring:
  config:
    activate:
      on-profile: test
user:
  service:
    uri: http://user-test:8081
course:
  service:
    uri: http://course-test:8082

gateway:
  cors:
    allowed-origins: "*"

logging:
  level:
    com.gitittogether.skillforge.server.gateway.LoggingGlobalFilter: WARN
