spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  port: ${SERVER_PORT_GATEWAY:8081}
  address: "0.0.0.0"

user:
  service:
    uri: http://localhost:${SERVER_PORT_USER:8082}
course:
  service:
    uri: http://localhost:${SERVER_PORT_COURSE:8083}

gateway:
  health:
    uri: http://localhost:${SERVER_PORT_GATEWAY:8081}

# Override Rate limiting configuration
rate:
  limit:
    requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:300}
    requests-per-second: ${RATE_LIMIT_REQUESTS_PER_SECOND:60}
    burst: ${RATE_LIMIT_BURST:50}
