spring:
  config:
    activate:
      on-profile: prod

server:
  port: ${SERVER_PORT_GATEWAY:8081}
  address: "0.0.0.0"

user:
  service:
    uri: http://user-service:${SERVER_PORT_USER:8082}
course:
  service:
    uri: http://course-service:${SERVER_PORT_COURSES:8083}

gateway:
  cors:
    allowed-origins: "*"