spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  port: ${SERVER_PORT_GATEWAY:8081}
  address: "0.0.0.0"

user:
  service:
    uri: http://${SERVER_HOST_USER:user-service}:${SERVER_PORT_USER:8082}
course:
  service:
    uri: http://${SERVER_HOST_COURSE:course-service}:${SERVER_PORT_COURSE:8083}

#Overide Rate limiting configuration for Docker
rate:
  limit:
    requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:60}
    requests-per-second: ${RATE_LIMIT_REQUESTS_PER_SECOND:10}
    burst: ${RATE_LIMIT_BURST:20}

gateway:
  health:
    uri: http://${SERVER_HOST_GATEWAY:server-gateway}:${SERVER_PORT_GATEWAY:8081}

logging:
  level:
    com.gitittogether.skillforge.server.gateway: INFO
    com.gitittogether.skillforge.server.gateway.config: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.springframework.data.redis: INFO
