spring:
  config:
    activate:
      on-profile: test

server:
  port: ${SERVER_PORT_GATEWAY:8080}
  address: "0.0.0.0"

user:
  service:
    uri: http://user-test:${SERVER_PORT_USER:8081}
course:
  service:
    uri: http://course-test:${SERVER_PORT_COURSES:8082}

gateway:
  cors:
    allowed-origins: "*"

logging:
  level:
    com.gitittogether.skillforge.server.gateway.LoggingGlobalFilter: WARN
