spring:
  config:
    activate:
      on-profile: docker

user:
  service:
    uri: http://user-service:8082
course:
  service:
    uri: http://course-service:8083


gateway:
  cors:
    allowed-origins: "*"
