server:
  port: ${SERVER_PORT_GATEWAY:8081}
  address: "0.0.0.0"

spring:
  application:
    name: SkillForge-gateway
  profiles:
    active: ${SPRING_PROFILE_ACTIVES:dev}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

jwt:
  secret: ${JWT_SECRET:default-secret-key-for-development-only-change-in-production}
  expirationMs: ${JWT_EXPIRATION_MS:86400000}

gateway:
  cors:
    allowed-origins: "*"

logging:
  level:
    com.gitittogether.skillforge.server.gateway: INFO
    com.gitittogether.skillforge.server.gateway.LoggingGlobalFilter: INFO
    com.gitittogether.skillforge.server.gateway.config: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO