version: '3.8'

services:
  # Weaviate Vector Database
  skillforge-weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
    container_name: skillforge-weaviate
    restart: on-failure
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - "8088:8080"
      - "50051:50051"
      - "2112:2112"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      BACKUP_FILESYSTEM_PATH: '/var/lib/weaviate/backups'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      PROMETHEUS_MONITORING_ENABLED: 'true'
    volumes:
      - weaviate-genai-data:/var/lib/weaviate
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 50s
    networks:
      - skillforge-network

  # SkillForge GenAI Service
  skillforge-genai:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GENAI_APP_NAME: "${GENAI_APP_NAME:-SkillForge GenAI}"
        GENAI_APP_VERSION: "${GENAI_APP_VERSION:-1.0.0-dev}"
        GENAI_PORT: ${GENAI_PORT:-8888}
        UVICORN_WORKERS: ${UVICORN_WORKERS:-2}
        CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-*}
    container_name: skillforge-genai
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WEAVIATE_HOST: ${WEAVIATE_HOST:-skillforge-weaviate}
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_PORT: 50051
      GENAI_PORT: ${GENAI_PORT:-8888}
      GENAI_APP_NAME: "${GENAI_APP_NAME:-SkillForge GenAI}"
      GENAI_APP_VERSION: "${GENAI_APP_VERSION:-1.0.0-dev}"
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-*}
      IS_DEV_MODE: 0
      UVICORN_WORKERS: ${UVICORN_WORKERS:-2}
      LLM_PROVIDER: ${LLM_PROVIDER:-openai}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
    ports:
      - "${GENAI_PORT:-8888}:${GENAI_PORT:-8888}"
    depends_on:
      skillforge-weaviate:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${GENAI_PORT:-8888}/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 50s
    networks:
      - skillforge-network
    volumes:
      - ./tmp:/app/tmp
      - ./logs:/app/logs

networks:
  skillforge-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1

volumes:
  weaviate-genai-data:
    driver: local 