global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  # ----- Spring Boot services (Micrometer) -----
  - job_name: spring-boot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - skillforge-gateway:8081
          - skillforge-user-service:8082
          - skillforge-course-service:8083

  # ----- GenAI FastAPI -----
  - job_name: genai
    metric_relabel_configs:
      # duplicate app label into app_name for FastAPI dashboard
      - source_labels: ["job"]
        target_label: "app_name"
        regex: "(.*)"
        replacement: "$1"
    static_configs:
      - targets: [ 'skillforge-genai:8888' ]

  # ----- Traefik Proxy -----
  - job_name: traefik
    metric_relabel_configs:
      # add static namespace label expected by upstream Traefik dashboard
      - target_label: "namespace"
        replacement: "default"
      # add service label for dashboard compatibility
      - target_label: "service"
        replacement: "traefik"
    static_configs:
      - targets: [ 'traefik:8085' ]

  # ----- Database exporters -----
  - job_name: mongo_exporter
    metric_relabel_configs:
      # rename job label so MongoDB dashboard variable matches
      - target_label: "job"
        replacement: "mongodb-exporter"
    static_configs:
      - targets: [ 'mongo-exporter:9216' ]

  - job_name: redis_exporter
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  # ----- Weaviate vector DB -----
  - job_name: weaviate
    metrics_path: /metrics
    static_configs:
      - targets: [ 'skillforge-weaviate:2112' ]
