{{- if and .Values.monitoring.enabled .Values.monitoring.alertmanager.enabled .Values.monitoring.alertmanager.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-alertmanager
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.alertmanager.storage.size }}
  {{- if .Values.monitoring.alertmanager.storage.storageClassName }}
  storageClassName: {{ .Values.monitoring.alertmanager.storage.storageClassName }}
  {{- end }}
{{- end }} 