{{- if and .Values.monitoring.enabled .Values.monitoring.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-alertmanager
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.monitoring.alertmanager.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
{{- end }} 