{{- if and .Values.monitoring.enabled .Values.monitoring.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-loki
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: loki
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.monitoring.loki.port }}
      targetPort: loki-port
      protocol: TCP
      name: http
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: loki
{{- end }} 