apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-mailhog
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    app.kubernetes.io/component: mailhog
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.monitoring.mailhog.webPort }}
    targetPort: web
    protocol: TCP
    name: web
  - port: {{ .Values.monitoring.mailhog.smtpPort }}
    targetPort: smtp
    protocol: TCP
    name: smtp
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mailhog 