{{- if and .Values.monitoring.enabled .Values.monitoring.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-promtail-config
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: promtail
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://skillforge-loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: system
        static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log

      - job_name: containers
        static_configs:
        - targets:
            - localhost
          labels:
            job: containerlogs
            __path__: /var/lib/docker/containers/*/*log

        pipeline_stages:
        - json:
            expressions:
              stream: stream
              attrs: attrs
              tag: attrs.tag
              time: time
        - labels:
            stream:
            tag:
        - timestamp:
            source: time
            format: RFC3339Nano
{{- end }} 