{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-prometheus-config
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']

    rule_files:
      - "alert.rules.yml"

    scrape_configs:
      # ----- Spring Boot services (Micrometer) -----
      - job_name: spring-boot
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - skillforge-gateway:8081
              - skillforge-user-service:8082
              - skillforge-course-service:8083

      # ----- GenAI FastAPI -----
      - job_name: genai
        metric_relabel_configs:
          # duplicate app label into app_name for FastAPI dashboard
          - source_labels: ["job"]
            target_label: "app_name"
            regex: "(.*)"
            replacement: "$1"
        static_configs:
          - targets: [ 'skillforge-genai-service:8888' ]

      # ----- Traefik Proxy -----
      - job_name: traefik
        metric_relabel_configs:
          # add static namespace label expected by upstream Traefik dashboard
          - target_label: "namespace"
            replacement: "default"
          # add service label for dashboard compatibility
          - target_label: "service"
            replacement: "traefik"
        static_configs:
          - targets: [ 'traefik:8085' ]

      # ----- Database exporters -----
      - job_name: mongo_exporter
        metric_relabel_configs:
          # rename job label so MongoDB dashboard variable matches
          - target_label: "job"
            replacement: "mongodb-exporter"
        static_configs:
          - targets: [ 'skillforge-mongo-exporter:9216' ]

      - job_name: redis_exporter
        static_configs:
          - targets: [ 'skillforge-redis:6379' ]

      # ----- Weaviate vector DB -----
      - job_name: weaviate
        metrics_path: /metrics
        static_configs:
          - targets: [ 'skillforge-weaviate:2112' ]

  alert.rules.yml: |
    groups:
      - name: basic-alerts
        rules:
          - alert: HighErrorRate
            expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) > 0.05
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High 5xx error rate across services"

          - alert: SlowResponses
            expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le)) > 1
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "95th percentile HTTP latency >1s"

          - alert: MongoExporterDown
            expr: up{job="mongo_exporter"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "MongoDB exporter is down"

          - alert: RedisExporterDown
            expr: up{job="redis_exporter"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Redis exporter is down"

          - alert: GenAIHighLatency
            expr: histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{handler="/api/v1/generate",job="genai"}[5m])) by (le)) > 0.1
            for: 30s
            labels:
              severity: warning
            annotations:
              summary: "GenAI service response time is high (>0.1s for 90th percentile)"
              description: "The GenAI service is experiencing high response times, which may affect user experience with AI-generated content."
          
          - alert: TestAlert
            expr: vector(1) > 0
            labels:
              severity: warning
            annotations:
              summary: "Test alert that should always fire"
              description: "This is a test alert that should always fire to verify alerting is working."
{{- end }} 