{{- if and .Values.monitoring.enabled .Values.monitoring.mongoExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exporter
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo-exporter
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "skillForgeAi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongo-exporter
  template:
    metadata:
      labels:
        {{- include "skillForgeAi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongo-exporter
    spec:
      containers:
      - name: mongo-exporter
        image: {{ .Values.monitoring.mongoExporter.image.repository }}:{{ .Values.monitoring.mongoExporter.image.tag }}
        ports:
        - containerPort: {{ .Values.monitoring.mongoExporter.port }}
          name: http
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongodbUri
        args:
        - --mongodb.uri=$(MONGODB_URI)
        - --no-mongodb.direct-connect
        - --collector.collstats
        - --collector.topmetrics
        - --collector.indexstats
        - --collector.dbstats
        - --discovering-mode
        - --compatible-mode
        - --web.listen-address=:{{ .Values.monitoring.mongoExporter.port }}
        resources:
          {{- toYaml .Values.monitoring.mongoExporter.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }} 