apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-weaviate-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.weaviate.storage.size }}