apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-weaviate
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: weaviate
spec:
  type: {{ .Values.weaviate.serviceType | default "ClusterIP" }}
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: weaviate
  ports:
    - protocol: TCP
      port: {{ .Values.ports.weaviate.http }}
      targetPort: weav-http
      name: http
    - protocol: TCP
      port: {{ .Values.ports.weaviate.grpc }}
      targetPort: weav-grpc
      name: grpc
    - protocol: TCP
      port: {{ .Values.ports.weaviate.prometheus }}
      targetPort: weav-prometheus
      name: prometheus