{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-prometheus-pvc
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.prometheus.storage.size }}
  {{- if .Values.monitoring.prometheus.storage.storageClassName }}
  storageClassName: {{ .Values.monitoring.prometheus.storage.storageClassName }}
  {{- end }}
{{- end }} 