{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-prometheus
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: prometheus
spec:
  type: ClusterIP
  selector:
    {{- include "skillForgeAi.selectorLabels" . | nindent 4 }}
    component: prometheus
  ports:
    - port: {{ .Values.monitoring.prometheus.port }}
      targetPort: prometheus-port
      protocol: TCP
      name: prometheus
{{- end }} 