{{- if and .Values.monitoring.enabled .Values.monitoring.loki.enabled .Values.monitoring.loki.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-loki-pvc
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.loki.storage.size }}
  {{- if .Values.monitoring.loki.storage.storageClass }}
  storageClassName: {{ .Values.monitoring.loki.storage.storageClass }}
  {{- end }}
{{- end }} 