{{- if and .Values.monitoring.enabled .Values.monitoring.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-loki-config
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: loki
data:
  loki-config.yml: |
{{ .Files.Get "monitoring/loki/loki-config.yml" | indent 4 }}
  promtail-config.yml: |
{{ .Files.Get "monitoring/loki/promtail-config.yml" | indent 4 }}
{{- end }}