{{- if and .Values.monitoring.enabled .Values.monitoring.loki.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-loki
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: loki
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "skillForgeAi.selectorLabels" . | nindent 6 }}
      component: loki
  template:
    metadata:
      labels:
        {{- include "skillForgeAi.selectorLabels" . | nindent 8 }}
        component: loki
    spec:
      securityContext:
        fsGroup: 65534
        supplementalGroups:
          - 65534
      containers:
        - name: loki
          image: "{{ .Values.monitoring.loki.image.repository }}:{{ .Values.monitoring.loki.image.tag }}"
          imagePullPolicy: {{ .Values.monitoring.loki.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.monitoring.loki.port }}
              name: loki-port
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
          args:
            - -config.file=/etc/loki/local-config.yaml
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /loki
          livenessProbe:
            httpGet:
              path: /ready
              port: loki-port
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: loki-port
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.monitoring.loki.resources.requests.cpu }}
              memory: {{ .Values.monitoring.loki.resources.requests.memory }}
            limits:
              cpu: {{ .Values.monitoring.loki.resources.limits.cpu }}
              memory: {{ .Values.monitoring.loki.resources.limits.memory }}
      volumes:
        - name: loki-config
          configMap:
            name: {{ include "skillForgeAi.fullname" . }}-loki-config
        - name: loki-data
          persistentVolumeClaim:
            claimName: {{ include "skillForgeAi.fullname" . }}-loki-pvc
{{- end }} 