{
 "title": "Redis Dashboard (Simplified)",
 "description": "Simplified Redis Dashboard for DevOps Project - Core Redis metrics only",
 "tags": [
  "prometheus",
  "redis",
  "simplified"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": "label_values(redis_up{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "instance",
    "query": "label_values(redis_up{namespace=\"$namespace\", pod=\"$pod_name\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Commands Processed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_keyspace_hits_total{instance=~\"$instance\"} / (redis_keyspace_hits_total{instance=~\"$instance\"} + redis_keyspace_misses_total{instance=~\"$instance\"}))",
     "legendFormat": "Hit ratio"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_rejected_connections_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "Rejected Connections"
    },
    {
     "expr": "rate(redis_rejected_connections_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}