{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-grafana-secret
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: grafana
type: Opaque
stringData:
  adminUser: {{ .Values.secrets.grafanaAdminUser | quote }}
  adminPassword: {{ .Values.secrets.grafanaAdminPassword | quote }}
{{- end }} 