apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-grafana-datasources
  labels:
    grafana_datasource: "1"
data:
    prometheus.yml: |
{{- .Files.Get "monitoring/grafana/provisioning/datasources/prometheus.yml" | nindent 4 }}
    loki.yml: |
{{- .Files.Get "monitoring/grafana/provisioning/datasources/loki.yml" | nindent 4 }}
