apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://skillforge-prometheus:9090
        uid: DS_PROMETHEUS
        isDefault: true
        jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"
          httpMethod: "POST"
      - name: Loki
        type: loki
        access: proxy
        url: http://skillforge-loki:3100
        uid: DS_LOKI
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: DS_PROMETHEUS
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "${__value.raw}"
        isDefault: false
        editable: true