{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-grafana
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "skillForgeAi.selectorLabels" . | nindent 6 }}
      component: grafana
  template:
    metadata:
      labels:
        {{- include "skillForgeAi.selectorLabels" . | nindent 8 }}
        component: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: "{{ .Values.monitoring.grafana.image.repository }}:{{ .Values.monitoring.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.monitoring.grafana.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.monitoring.grafana.port }}
              name: grafana-port
          env:
            - name: GF_SERVER_ROOT_URL
              value: "https://grafana.student.k8s.aet.cit.tum.de/"
            - name: GF_SERVER_HTTP_PORT
              value: "{{ .Values.monitoring.grafana.port }}"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "{{ .Values.monitoring.grafana.adminPassword }}"
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "publicDashboards"
            - name: GF_UNIFIED_ALERTING_ENABLED
              value: "true"
            - name: GF_ALERTING_ENABLED
              value: "false"
          securityContext:
            runAsNonRoot: true
            runAsUser: 472
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
          livenessProbe:
            httpGet:
              path: /api/health
              port: grafana-port
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: grafana-port
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.monitoring.grafana.resources.requests.cpu }}
              memory: {{ .Values.monitoring.grafana.resources.requests.memory }}
            limits:
              cpu: {{ .Values.monitoring.grafana.resources.limits.cpu }}
              memory: {{ .Values.monitoring.grafana.resources.limits.memory }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "skillForgeAi.fullname" . }}-grafana-pvc
        - name: datasources
          configMap:
            name: {{ include "skillForgeAi.fullname" . }}-grafana-datasources
        - name: dashboards-config
          configMap:
            name: {{ include "skillForgeAi.fullname" . }}-grafana-dashboard-provider
        - name: dashboards
          configMap:
            name: {{ include "skillForgeAi.fullname" . }}-grafana-dashboards
{{- end }}