server:
  port: ${SERVER_PORT_USER:8082}
  address: "0.0.0.0"


spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGO_URL}