server:
  port: ${SERVER_PORT_USER:8081}
  address: "0.0.0.0"

spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      database: test-db

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}
