server:
  port: ${SERVER_PORT_USER:8082}
  address: "0.0.0.0"

spring:
  application:
    name: SkillForge-user-service
  profiles:
    active: ${SPRING_PROFILE_ACTIVES:dev}
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    enabled: true
    path: /docs/api
  swagger-ui:
    enabled: true
    path: /docs

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

jwt:
  secret: ${JWT_SECRET:dev-secret-key-for-development-only-change-in-production}
  expirationMs: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: WARN