server:
  port: ${SERVER_PORT_USER:8082}
  address: "0.0.0.0"

spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      database: ${MONGODB_DATABASE:skillforge}
      uri: ${MONGO_URL:mongodb://localhost:27017/skillforge}