{{- if and .Values.monitoring.enabled .Values.monitoring.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillForgeAi.fullname" . }}-alertmanager
  labels:
    {{- include "skillForgeAi.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "skillForgeAi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "skillForgeAi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      securityContext:
        fsGroup: 65534
        supplementalGroups:
          - 65534
      containers:
      - name: alertmanager
        image: {{ .Values.monitoring.alertmanager.image.repository }}:{{ .Values.monitoring.alertmanager.image.tag }}
        ports:
        - containerPort: {{ .Values.monitoring.alertmanager.port }}
          name: http
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - name: config
          mountPath: /etc/alertmanager
        - name: data
          mountPath: /alertmanager
        resources:
          {{- toYaml .Values.monitoring.alertmanager.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: {{ include "skillForgeAi.fullname" . }}-alertmanager-config
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "skillForgeAi.fullname" . }}-alertmanager
{{- end }} 