server:
  port: ${SERVER_PORT_COURSES:8083}
  address: "0.0.0.0"

spring:
  application:
    name: SkillForge-course-service
    version: ${APP_VERSION:0.0.1-SNAPSHOT}
  profiles:
    active: ${SPRING_PROFILE_ACTIVES:dev}
  web:
    resources:
      add-mappings: true

springdoc:
  api-docs:
    enabled: false
    url: /api/v1/courses/docs/course-openapi.yaml
  swagger-ui:
    enabled: true
    url: /docs/course-openapi.yaml

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,openapi,swagger-ui

jwt:
  secret: ${JWT_SECRET:dev-insecure-key-change-me}
  expirationMs: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: WARN
    com.gitittogether.skillforge: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | [%thread] | %logger{20} | %msg%n"
