server:
  port: ${SERVER_PORT_COURSES:8083}
  address: "0.0.0.0"

spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://testuser:testpass@localhost:27017/test-db?authSource=admin

jwt:
  secret: ${JWT_SECRET:test-secret}
  expirationMs: ${JWT_EXPIRATION_MS:3600000}
