server:
  port: ${SERVER_PORT_COURSES:8083}
  address: "0.0.0.0"


spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: ${MONGO_URL}

user:
  service:
    uri: http://${SERVER_HOST_USER:user-service}:${SERVER_PORT_USER:8082}