name: Build and Test Client

on:
  push:
    branches: [main, test, dev]
    paths:
      - 'client/**'
  pull_request:
    branches: [main, test, dev]
    paths:
      - 'client/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test-client:
    name: Build & Test Client
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
        continue-on-error: true

      - name: Run tests if test files exist (.test.* or in __tests__ directories)
        run: |
          # Only look in directories that exist to avoid find errors
          paths=""
          [ -d src ] && paths="$paths src"
          [ -d test ] && paths="$paths test"

          if [ -n "$paths" ]; then
            test_files=$(find $paths -type f \( -name "*.test.js" -o -name "*.test.jsx" -o -name "*.test.ts" -o -name "*.test.tsx" -o -path "*/__tests__/*" \) 2>/dev/null)
            if [ -n "$test_files" ]; then
              echo "Test files found:"
              echo "$test_files"
              npm run test
            else
              echo "No test files found (no *.test.* or __tests__/*). Skipping tests."
            fi
          else
            echo "No test or src directories found, skipping tests."
          fi

      - name: Build client
        run: npm run build
        env:
          VITE_APP_NAME: SkillForge.ai
          VITE_APP_VERSION: 1.0-test
          VITE_API_BASE_URL: /api/
          VITE_API_VERSION: v1
          BUILD_MODE: production
          VITE_PUBLIC_API_URL: http://server.localhost:8081/api
          VITE_API_INTERNAL_HOST: server-gateway
          VITE_API_INTERNAL_PORT: 8081
          VITE_PORT: 3000

      - name: Verify build output
        run: |
          if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
            echo "Build output found - Build and Test Client workflow completed successfully."
          else
            echo "No build output found - Build and Test Client workflow failed."
            exit 1
          fi

