name: Build, Push and Deploy to Kubernetes

on:
  workflow_dispatch:
# Currently we deploy only on manual trigger. 
  #push:
   # branches:
    #  - main
      
jobs:
  build-and-test-client:
    name: Build and Test SkillForge.ai Client
    uses: ./.github/workflows/build-and-test-client.yml
  build-and-test-server:
    name: Build and Test SkillForge.ai Server
    uses: ./.github/workflows/build-and-test-server.yml
  build-and-test-sgenai:
    name: Build and Test SkillForge.ai GenAI
    uses: ./.github/workflows/build-and-test-genai.yml
  build-and-push-images:
    name: Build and Push Docker Images
    uses: ./.github/workflows/docker-build-push.yml
  # For demo purposes, we will deploy only on manual trigger (run provision_configure-deploy workflow)  
  #provision-configure-deploy:
   # name: Provision, Configure and Deploy to AWS
   # uses: ./.github/workflows/provision_configure_deploy.yml
   # with:
    #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    # TF_TOKEN: ${{ secrets.TF_TOKEN }}
    # AWS_REGION: ${{ secrets.AWS_REGION }}
  deploy-to-kubernetes:
    name: Deploy to Kubernetes Cluster (Rancher Cluster)
    needs: [build-and-push-images]
    uses: ./.github/workflows/deploy-to-kubernetes.yml
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
