name: Deploy to Kubernetes Cluster (Rancher Cluster)

# This workflow is triggered only when called by another workflow.
on:
  workflow_call:
    # Pass KUBECONFIG as a secret
    secrets:
      KUBECONFIG:
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    - name: Install Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: latest

    - name: Load Kubeconfig
      run: |
        mkdir -p ~/.kube
        printf "%s" "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config
    - name: Verify Kubeconfig
      run: |
        kubectl config view
        kubectl get nodes

    - name: Verify Helm
      run: |
        helm version
    
    - name: lint Helm Chart
      run: |
        helm lint ./deployment/k8s

    - name: Upgrade Deployment with Helm
      run: |
        helm upgrade --install meetatmensa ./deployment/k8s -n devoops