# This workflow performs a manual deployment of Docker images to an AWS EC2 instance
# via SSH/SCP. It is intended for manual operations. For full automation,
# see the automated deployment workflow (.github/workflows/deploy_to_aws.yml, which is run once provisioning (provision_configure_deploy_aws.yml) is done.


name: Manual Deploy to AWS

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: AWS
      url: 'https://client.${{ vars.EC2_PUBLIC_IP }}.nip.io'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Test SSH, disk space & Docker registry
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            set -e
            echo "Testing disk space:"
            df -h /
            echo "Testing Docker:"
            docker ps
            echo "Testing Docker registry login:"
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "All initial checks passed."
      - name: Copy Docker Compose File From Repo to the EC2 Instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: "./docker-compose.prod.yml"
          target: /home/${{ vars.AWS_EC2_USER }}

      - name: Get latest tag (or use 1.0-alpha as fallback)
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0-alpha")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Latest tag is: $TAG"

      - name: Prepare Environment File (.env)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
              set -e
              cd /home/${{ vars.AWS_EC2_USER }}
              rm -f .env
              echo "Creating .env file..."
              
              echo "APP_VERSION=${{ steps.get_tag.outputs.tag }}" >> .env
              echo "VITE_APP_VERSION=${{ steps.get_tag.outputs.tag }}" >> .env
              echo "GENAI_APP_VERSION=${{ steps.get_tag.outputs.tag }}" >> .env
  
              echo "SPRING_PROFILES_ACTIVE=prod" >> .env
              
              echo "MONGO_URL=${{ secrets.MONGODB_URL }}" >> .env
              echo "MONGODB_DATABASE=SkillForge" >> .env
              
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
              
              echo "OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}" >> .env
              echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
              echo "OPENAI_MODEL=gpt-4o" >> .env
              echo "UVICORN_WORKERS=${{ vars.UVICORN_WORKERS }}" >> .env
              
              echo "VITE_PUBLIC_API_URL=https://api.${{ vars.EC2_PUBLIC_IP }}.nip.io/api" >> .env
              echo "CLIENT_HOST=client.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "SERVER_HOST=api.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "GENAI_HOST=api.genai.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "MAILHOG_HOST=mail.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "PROMETHEUS_HOST=prometheus.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "LOKI_HOST=loki.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "PROMTAIL_HOST=promtail.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "ALERTMANAGER_HOST=alertmanager.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
              echo "GRAFANA_HOST=grafana.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
  
              chmod 600 .env
              echo ".env file created ✅"
      - name: SSH to the EC2 Instance and Start Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        timeout-minutes: 10
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/${{ vars.AWS_EC2_USER }}
            echo " >>> Logging into Docker registry..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo " >>> Starting Docker Compose..."
            if ! docker compose -f docker-compose.prod.yml --env-file .env up --pull=always -d --remove-orphans; then
              echo "❌ Docker Compose failed. Showing service status:"
              docker compose -f docker-compose.prod.yml ps
              echo "-----------------------------------------"
              echo "------------ Recent logs ----------------"
              docker compose -f docker-compose.prod.yml logs --tail=40
              exit 1
            fi
      - name: Echo all links
        run: |
          echo "Deployment complete! Access your services at:"
          echo "Client: https://client.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "API: https://api.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "GenAI: https://api.genai.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Mailhog: https://mail.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Prometheus: https://prometheus.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Loki: https://loki.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Promtail: https://promtail.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Alertmanager: https://alertmanager.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Grafana: https://grafana.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Check the status of your services with:"
          echo "docker compose -f docker-compose.prod.yml ps"
          echo "View logs with:"
          echo "docker compose -f docker-compose.prod.yml logs --tail=40"