# This workflow performs a manual deployment of Docker images to an AWS EC2 instance
# via SSH/SCP. It is intended for legacy/manual operations. For full automation,
# see the automated deployment workflow (.github/workflows/auto_docker_deploy_to_aws.yml).


name: Manual Deploy to AWS

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: AWS
      url: 'https://client.${{ vars.EC2_PUBLIC_IP }}.nip.io'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Test SSH, disk space & Docker registry
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            set -e
            echo "Testing disk space:"
            df -h /
            echo "Testing Docker:"
            docker ps
            echo "Testing Docker registry login:"
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "All initial checks passed."
      - name: Copy Docker Compose File From Repo to the EC2 Instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: "./docker-compose.prod.yml"
          target: /home/${{ vars.AWS_EC2_USER }}

      - name: Get latest tag (or use 1.0-alpha as fallback)
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0-alpha")
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Latest tag is: $TAG"

      - name: Prepare Environment File (.env)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          # TODO: Add echo "MONGODB_DATABASE=\"vars.MONGODB_DATABASE \"" >> .env
          #      echo "MONGODB_USERNAME=\"$secrets.MONGODB_USERNAME\"" >> .env
          # Once updated
          script: |
            set -e
            cd /home/${{ vars.AWS_EC2_USER }}
            rm -f .env
            echo "Creating .env file..."

            echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> .env

            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_EXPIRATION_MS=${{ vars.JWT_EXPIRATION_MS }}" >> .env

            echo "VITE_APP_NAME=SkillForge.ai" >> .env
            echo "VITE_APP_VERSION=${{ steps.get_tag.outputs.tag }}" >> .env

            echo "GENAI_APP_VERSION=${{ steps.get_tag.outputs.tag }}" >> .env
            echo "UVICORN_WORKERS=${{ vars.UVICORN_WORKERS }}" >> .env
            echo "LLM_PROVIDER=${{ vars.LLM_PROVIDER }}" >> .env
            echo "OPENAI_API_BASE=${{ vars.OPENAI_API_BASE }}" >> .env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
            echo "OPENAI_MODEL=${{ vars.OPENAI_MODEL }}" >> .env

            echo "CLIENT_HOST=client.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
            echo "SERVER_HOST=api.${{ vars.EC2_PUBLIC_IP }}.nip.io" >> .env
            echo "VITE_PUBLIC_API_URL=https://api.${{ vars.EC2_PUBLIC_IP }}.nip.io/api" >> .env
            echo "VITE_API_INTERNAL_HOST=server-gateway" >> .env
            echo "VITE_API_INTERNAL_PORT=8081" >> .env

            chmod 600 .env
            echo ".env file created ✅"
      - name: SSH to the EC2 Instance and Start Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        timeout-minutes: 10
        with:
          host: ${{ vars.EC2_PUBLIC_IP }}
          username: ${{ vars.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/${{ vars.AWS_EC2_USER }}
            echo " >>> Logging into Docker registry..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo " >>> Starting Docker Compose..."
            if ! docker compose -f docker-compose.prod.yml --env-file .env up --pull=always -d --remove-orphans; then
              echo "❌ Docker Compose failed. Showing service status:"
              docker compose -f docker-compose.prod.yml ps
              echo "-----------------------------------------"
              echo "------------ Recent logs ----------------"
              docker compose -f docker-compose.prod.yml logs --tail=40
              exit 1
            fi
      - name: Echo all links
        run: |
          echo "Deployment complete! Access your services at:"
          echo "Client: https://client.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "API: https://api.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "GenAI: https://genai.${{ vars.EC2_PUBLIC_IP }}.nip.io"
          echo "Check the status of your services with:"
          echo "docker compose -f docker-compose.prod.yml ps"
          echo "View logs with:"
          echo "docker compose -f docker-compose.prod.yml logs --tail=40"